// tslint:disable
/**
 * New Ambition
 * New Ambition REST API
 *
 * OpenAPI spec version: 1.1.0
 * Contact: federico.pastore@bnlmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
